[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.9
dynamic_padding = true
blur = true

[window.padding]
x = 15
y = 15

[window.dimensions]
columns = 120
lines = 36

[selection]
save_to_clipboard = true
